version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100m"
    max-file: "100"

networks:
  common-net: {}

services:
  postgres_db:
    container_name: posta_cloud_db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_LOGGING_COLLECTOR=true
      - POSTGRESQL_LOG_MIN_ERROR_STATEMENT=error
      - POSTGRESQL_LOG_STATEMENTS=all
    logging: *default-logging

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ASSET_URL=${VITE_ASSET_URL}
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - BASE_URL=${VITE_ASSET_URL}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    depends_on:
      - elasticsearch
      - postgres_db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db-data:
